#pragma once

#include <gtest/gtest.h>

#define JTEST_NAME(SUITE, NAME) GTEST_TEST(SUITE, NAME)
#define JTEST_TRUE(CONDITION) EXPECT_TRUE(CONDITION)
#define JTEST_EQ(VALUE1, VALUE2) EXPECT_EQ(VALUE1, VALUE2)
