:last-update-label!:
:source-highlighter: highlight.js
:highlightjsdir: highlight

= Backend in C++

== Library

=== Export the interface

The whole backend is build in a single library.

The library must be buildable with option `-fvisibility=hidden`. So all symbols that need to be used must be explicitly exported.

For this job, it will be used:

- `\__declspec(dllimport)` and `__declspec(dllexport)` will be used for https://docs.microsoft.com/en-us/cpp/build/importing-and-exporting[Windows],
- `\\__attribute__((visibility("default")))` will be used for Linux.

Internally, `JESSICA_BUILDING_DLL` will be defined.

== Manage data

Data are stored in class.

Each of these class have two classes: an adapter and the implementation.
Between adapter and implementation, you may add decorators.

=== History

At first, each adapter inherited from a https://github.com/bansan85/jessica/blob/5860d813a852e68cf2cb9be009fce03d7b39dc39/include/jessica/data/load/vertical_eccentric.h[pure virtual class].

Then adapter needed to be templated to support decorator, I decided to use https://github.com/bansan85/jessica/blob/4e7884bb98f24c3a1146a1ef0119f20ab84023c1/include/jessica/data/load/vertical_eccentric_concept.h[concept] with accessor.

I needed to have a very generic getter and setter to reduce the need of boilerplate to access multiple levels of data. There is only https://github.com/bansan85/jessica/blob/4e7884bb98f24c3a1146a1ef0119f20ab84023c1/include/jessica/calc/geotechnical/meyerhof.h[one primary template function `f` for accessor]. Specialization when needed is done with `requires` keyword (`C++20`) instead of template specialization or use of `std::enable_if<>`. I removed concept interface because it can not force specialization of primary template.

The use of `f` is inconventional. I hide it inside the decorator class. To simplify the use of a generic decorator, I created macro to avoid copy / paste and ease maintainability.

GoogleTest supports mocking with template.

=== Class

Getters have bare name. Setter have `Set` has prefix name.

Data are immutable so setters return a copy of the object. The copy is done by `Clone` function.

The `Rule of five` is applied. Copy constructor must be public to use `std::make_shared`.

Example of a simple class:

[source,cpp]
----
#include <limits>
#include <memory>

#include <jessica/compat.h>

class JESSICA_DLL_PUBLIC FoundationStrip final
{
 public:
  FoundationStrip() = default;
  FoundationStrip(const FoundationStrip&) = default;
  FoundationStrip(FoundationStrip&&) = delete;
  FoundationStrip& operator=(const FoundationStrip&) = delete;
  FoundationStrip& operator=(FoundationStrip&&) = delete;

  ~FoundationStrip() = default;

  [[nodiscard]] std::shared_ptr<FoundationStrip> Clone() const
  {
    return std::make_shared<FoundationStrip>(*this);
  }

  [[nodiscard]] double B() const { return b_; }

  [[nodiscard]] std::shared_ptr<FoundationStrip> SetB(const double b) const
  {
    auto retval = Clone();
    retval->b_ = b;
    return retval;
  }

 private:
  double b_ = std::numeric_limits<double>::quiet_NaN();
};
----

=== Adapters

All decorators use the same template function `f`. The goal is to be able to implement only one generic function that may be applied to all functions.

You will need two adapters. One at the beginning to convert getters and setters to the `f` template function. The second at the end to convert `t` template function to getters and setters.

  * Coding style

Ownership of a return value of a setter must be able to be shared. Use a `std::shared_ptr<>`. Pass them by const reference in function and store them by copy in class.

  * Example of declaration

If you do not need decorator, just use `FoundationStrip`.

If you need decorator, you have to create `DecoratorStartFoundationStrip` and `DecoratorEndFoundationStrip` around decorator(s).

Use `DecoratorStartFoundationStrip<LogCall<DecoratorEndFoundationStrip<FoundationStrip>>>`.

  * Implementation of `DecoratorStartFoundationStrip`:

The goal of DecoratorStartFoundationStrip is to convert getter `B` and setter `SetB` to `f` template functions.

This code heavily uses macro.

[source,cpp]
----
#include <memory>

#include <jessica/util/decorator/end.h>
#include <jessica/util/decorator/macro.h>
#include <jessica/util/decorator/start.h>

template <typename T>
class JESSICA_DLL_PUBLIC DECORATOR_START_HEADER(FoundationStrip)
{
 public:
  DECORATOR_START_RULE_OF_FIVE(FoundationStrip);

  DECORATOR_CLONE(FoundationStrip)

  DECORATOR_START_GET(B)
  DECORATOR_START_SET(FoundationStrip, B)
};

template <typename T>
class JESSICA_DLL_PUBLIC DECORATOR_END_HEADER(FoundationStrip)
{
 public:
  using RootType = T;

  DECORATOR_END_RULE_OF_FIVE(FoundationStrip);

  DECORATOR_END_GET(B)
  DECORATOR_END_SET(B)
};
----

=== Decorator

Decorators is added between between `DecoratorStart` and DecoratorEnd`.

They implement the same `f` functions. If needed, you can specialize some of them.

You need to pass `impl` to all constructor of decorator. Only `DecoratorEnd` knows the type of the final template type. And `impl` is stored in `DecoratorStart` to ease clone due to functional style.

[source,cpp]
----
namespace jessica
{
template <typename T>
class JESSICA_DLL_PUBLIC LogDuration
{
 public:
  using RootType = typename T::RootType;

  template <typename... Args>
  LogDuration(std::shared_ptr<RootType>& impl,
              std::shared_ptr<spdlog::logger> log, Args&&... args)
      : t(impl, std::forward<Args>(args)...), log_(std::move(log))
  {
  }
  LogDuration(const LogDuration&) = default;
  LogDuration(LogDuration&&) = delete;
  LogDuration& operator=(const LogDuration&) = delete;
  LogDuration& operator=(LogDuration&&) = delete;

  ~LogDuration() = default;

  template <uint64_t Action, uint64_t... U, typename... Args>
  [[nodiscard]] auto f(const RootType& classe, Args&&... args) const
  {
    const auto t_start = std::chrono::high_resolution_clock::now();
    auto retval =
        t.template f<Action, U...>(classe, std::forward<Args>(args)...);
    const auto t_end = std::chrono::high_resolution_clock::now();
    const double elapsed_time_ms =
        std::chrono::duration<double, std::milli>(t_end - t_start).count();
    log_->info("duration " + cfi_to_string(elapsed_time_ms) + " ms");
    return retval;
  }

 private:
  T t;

  std::shared_ptr<spdlog::logger> log_;
};
}  // namespace jessica
----

=== All together

You can create the data without decorator.

[source,cpp]
----
  const auto foundation = std::make_shared<FoundationStrip>();
----

or with decorator.

[source,cpp]
----
  using Decorator =
      DecoratorStartFoundationStrip<LogCall<LogDuration<DecoratorEndFoundationStrip<FoundationStrip>>>>;

  const auto foundation = std::make_shared<Decorator>();
----

After, use the instance like that:

[source,cpp]
----
  const auto foundation = std::make_shared<DecoratorFoundation>(log, log);
  const auto foundation2 = foundation->SetB(1.);
  assert(foundation->B() == 1.);
----

=== Data inside data

Some classes need to store data from other class.

In this case, you may, or not, allow children classes to be decorated.

To access children data, you need to pass the pointer of the function then after the arguments.
It will may change in the future but it's the best I found for the current time.

  * Adapter

For example, Meyerhof have two data stored.

An example with only decorator to the main class:

[source,cpp]
----
  // Data 1 without decorator
  using DecoratorFoundation = FoundationStrip;
  // Data 2 without decorator
  using DecoratorLoad = VerticalEccentric;
  // Main data with 2 data stored inside.
  using DecoratorCalc =
      DecoratorStartMeyerhof<LogCall<LogDuration<DecoratorEndMeyerhof<
          MeyerhofShallowFoundation<DecoratorLoad, DecoratorFoundation>>>>>;

  const auto calc = std::make_shared<DecoratorCalc>(load, foundation);
----

And the same with a decorator for every data:

[source,cpp]
----
  // Data 1 with decorator
  using DecoratorFoundation = DecoratorStartFoundationStrip<
      LogCall<LogDuration<DecoratorEndFoundationStrip<FoundationStrip>>>>;
  // Data 2 with decorator
  using DecoratorLoad = DecoratorStartVerticalEccentric<
      LogCall<LogDuration<DecoratorEndVerticalEccentric<VerticalEccentric>>>>;
  // Main data with 2 data stored inside.
  using DecoratorCalc =
      DecoratorStartMeyerhof<LogCall<LogDuration<DecoratorEndMeyerhof<
          MeyerhofShallowFoundation<DecoratorLoad, DecoratorFoundation>>>>>;

  const auto calc = std::make_shared<DecoratorCalc>(load, foundation);
----

  * Implementation

The implementation needs to have as template the type of data store (`T0` and `T1`).

[source,cpp]
----
namespace jessica
{
template <typename T0, typename T1>
class JESSICA_DLL_PUBLIC MeyerhofShallowFoundation final
{
 public:
  MeyerhofShallowFoundation(std::shared_ptr<T0> load,
                            std::shared_ptr<T1> foundation)
      : load_(std::move(load)), foundation_(std::move(foundation))
  {
  }
  RULE_OF_FIVE_COPY_AND_CLONE(MeyerhofShallowFoundation)

  [[nodiscard]] double B_() const { return foundation_->B() - 2. * load_->E(); }

  [[nodiscard]] double Qref() const { return load_->V() / B_(); }

  POCO_GET_FUNCTION(Foundation, foundation_)
  POCO_SET_FUNCTION(MeyerhofShallowFoundation, Foundation, foundation_)

  POCO_GET_FUNCTION(Load, load_)
  POCO_SET_FUNCTION(MeyerhofShallowFoundation, Load, load_)

 private:
  std::shared_ptr<T0> load_;
  std::shared_ptr<T1> foundation_;
};
}  // namespace jessica
----
