:last-update-label!:
:source-highlighter: highlight.js
:highlightjsdir: highlight

= Building

== How to

=== Linux

[source,sh]
----
mkdir build
cmake -S . -B build
cmake --build build/ --target all
cd build
ctest --output-on-failure
cd ..
----

=== Windows

[source,sh]
----
.\vcpkg\bootstrap-vcpkg.bat
.\vcpkg\vcpkg install "@.\config\cmake\vcpkg_x64-windows.txt"
mkdir build
cmake -S . -B build -G "Visual Studio 16 2019" -A x64 -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake
cmake --build build --target ALL_BUILD --config Debug
cd build
ctest -C Debug --output-on-failure
cd ..
----

=== Web Assembly

You need to install https://emscripten.org/docs/getting_started/downloads.html[Emscripten].

Run once:

[source,sh]
----
git clone --depth=1 https://github.com/emscripten-core/emsdk.git
cd emsdk
./emsdk install latest
./emsdk activate latest
----

Run everytime:

[source,sh]
----
source ./emsdk/emsdk_env.sh
mkdir build
emcmake cmake -S . -B build
emcmake cmake --build build/ --target all
cd build
ctest --output-on-failure
cd ..
----

== Dependencies

=== Building

Tools needed:

  * Compiler: gcc, clang or Visual Studio with C++20 support,
  * https://cmake.org/[cmake].

=== Backend

No dependencies.

=== Tests

You need:

  * https://github.com/google/googletest[gtest].

=== Documentation

You need https://highlightjs.org[highlight.js].

Build it with:

[source,sh]
----
node tools/build.js -t browser bash cpp xml javascript yaml
----

== Continuous integration

=== Tools

The build is tested with Ubuntu-LTS with gcc and clang and Windows with Visual Studio.

  * Linux

Compilers tested : gcc-11 and clang-12.

Packages are installed with ''apt-get''.

  * Windows

Compilers tested : Visual Studio 2019.

Packages are installed with ''vcpkg''.

=== Auto formatting

Don't spend to much time about formatting. Continuous integration will automatically create commit to fix them with https://github.com/cheshirekow/cmake_format[cmake-format] and https://clang.llvm.org/docs/ClangFormat.html[clang-format].

This is done in the `format` workflow. If a file need to be formatted, a new commit is added with a fix and the current build and next workflows will fail.

GitHub does not support two things:

  * When a workflow runs when another workflow has finished, the result is not added to the status of the commit. https://github.com/bansan85/action-workflow_run-status[action-workflow_run-status] fix it.
  * The start of a workflow that runs on `completed` event does not depend on the success or the failure of the previous workflow. Use the following code to fix it.

[source,yml]
----
      - name: Stop if format failed
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: exit 1
----

=== Linters

Lots (maybe too much) of linters are used:

  * yaml: https://github.com/adrienverge/yamllint[yamllint],
  * bash: https://github.com/koalaman/shellcheck[shellcheck],
  * requirements.txt: https://github.com/pyupio/safety[safety],
  * c++: https://include-what-you-use.org/[iwyu], http://cppcheck.sourceforge.net/[cppcheck], https://clang.llvm.org/extra/clang-tidy/[clang-tidy].
  * javascript: https://eslint.org/[ESLint],
  * css: https://stylelint.io/[stylelint],
  * html: https://prettier.io[prettier]

=== Sanitizers

Enable all sanitizers : address, thread, leak, undefined, cfi.

=== Data generated

I decided to use my own interface in addition to other well-integrated softwares like https://codecov.io[codecov] to keep data under control.

All data are stored in https://github.com/bansan85/jessica-ci[jessica-ci] repository.

Every commit, following data are generated:

[cols="1,1,3"] 
|===
|Data |Git branch |Description

|Tests
|ubuntu-clang,
ubuntu-gcc,
windows-msbuild,
emscripten.
|Duration of each tests,
List of installed packages for Linux.

|Coverage
|coverage-clang,
coverage-gcc.
|Coverage information.
Should be the same with both compilers.

|Documentation
|documentation
|HTML documentation.

|Metrics
|metrics
|Complexity and length of functions.

|===
