:last-update-label!:
:source-highlighter: highlight.js
:highlightjsdir: highlight

= Building

== Dependencies

=== Building

Tools needed:

  * Compiler: gcc, clang or Visual Studio with C++20 support,
  * https://cmake.org/[cmake].

=== Backend

  * logger: https://github.com/gabime/spdlog[spdlog]
  * serialization (data storage / send data to web services): https://uscilab.github.io/cereal/[cereal]

=== Frontend

  * https://nodejs.org/en/[Node.js] 14
  * https://angular.io/[Angular] 12

=== Tests

You need:

  * https://github.com/google/googletest[gtest].

=== Documentation

You need https://highlightjs.org[highlight.js].

Build it with:

[source,sh]
----
node tools/build.js -t browser bash cpp xml javascript yaml typescript
----

== How to

=== Requirements

  * cmake

To custom C++ flags, add to the first call of cmake `-DCMAKE_CXX_FLAGS=...`.

=== Linux

[source,sh]
----
mkdir -p build/gcc
cmake -S . -B build/gcc
cmake --build build/gcc --target all -j9
cd build/gcc
ctest --output-on-failure
cd ..
----

To build for a specific version of GCC:

[source,sh]
----
cmake -S . -B build/gcc -DCMAKE_C_COMPILER="/usr/bin/gcc-11" -DCMAKE_CXX_COMPILER="/usr/bin/g++-11" -DCMAKE_AR="/usr/bin/ar" -DCMAKE_RANLIB="/usr/bin/ranlib" -DCMAKE_CXX_FLAGS="-DSPDLOG_FMT_EXTERNAL -DFMT_HEADER_ONLY"
----

and for Clang:

[source,sh]
----
cmake -S . -B build/clang -DCMAKE_C_COMPILER="/usr/bin/clang-13" -DCMAKE_CXX_COMPILER="/usr/bin/clang++-13" -DCMAKE_AR="/usr/bin/llvm-ar-13" -DCMAKE_RANLIB="/usr/bin/llvm-ranlib-13" -DCMAKE_CXX_FLAGS="-DSPDLOG_FMT_EXTERNAL -DFMT_HEADER_ONLY"
----

=== Windows

From PowerShell:

[source,sh]
----
.\vcpkg\bootstrap-vcpkg.bat
.\vcpkg\vcpkg.exe install "@.\config\vcpkg_windows.txt" --triplet=x64-windows
.\vcpkg\vcpkg.exe integrate install
mkdir -p build\windows
cmake -S FULLPATH -B FULLPATH\build\windows -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE=FULLPATH\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_CXX_FLAGS="-DSPDLOG_FMT_EXTERNAL -DFMT_HEADER_ONLY"
cmake --build FULLPATH\build\windows --target ALL_BUILD --config Debug -j9
cd build\windows
ctest -C Debug --output-on-failure
cd ..
----

=== Web Assembly

You need to install https://emscripten.org/docs/getting_started/downloads.html[Emscripten].

Run once:

[source,sh]
----
git clone --depth=1 https://github.com/emscripten-core/emsdk.git
cd emsdk
./emsdk install latest
./emsdk activate latest
----

To update emsdk, run:
[source,sh]
----
cd emsdk
git pull
./emsdk install latest
./emsdk activate latest
----

Run everytime to build the project:

[source,sh]
----
source ./emsdk/emsdk_env.sh
./vcpkg/bootstrap-vcpkg.sh
./vcpkg/vcpkg install "@./config/vcpkg_emscripten.txt" --triplet=wasm32-emscripten
./vcpkg/vcpkg integrate install

mkdir build/angular_debug
emcmake cmake -S . -B build/angular_debug/ -DCMAKE_BUILD_TYPE=Debug -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/root/prog/emscripten/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DVCPKG_TARGET_TRIPLET=wasm32-emscripten -DCMAKE_TOOLCHAIN_FILE=/mnt/c/j/vcpkg/scripts/buildsystems/vcpkg.cmake
cmake --build build/angular_debug/ --target all --config Debug -j9
cd build
ctest --output-on-failure
cd ..

mkdir build/angular_release
emcmake cmake -S . -B build/angular_release/ -DCMAKE_BUILD_TYPE=Release -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/root/prog/emscripten/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DVCPKG_TARGET_TRIPLET=wasm32-emscripten -DCMAKE_TOOLCHAIN_FILE=/mnt/c/j/vcpkg/scripts/buildsystems/vcpkg.cmake
cmake --build build/angular_release/ --target all --config Release -j9
cd build
ctest --output-on-failure
cd ..
----

== Continuous integration

=== Tools

The build is tested with Ubuntu-LTS with gcc and clang and Windows with Visual Studio.

  * Linux

Compilers tested: gcc-11 and clang-13.

Packages are installed with `apt-get`.

  * Windows

Compilers tested: `Visual Studio 2019` with `Desktop development with C++`.

Packages are installed with `vcpkg`.

=== Auto formatting

This is done in the `format` workflow. If a file needs to be formatted, an artifact is added with a fix and the current build and next workflows will fail.

Formatters use:

  * backend: https://github.com/cheshirekow/cmake_format[cmake-format], https://clang.llvm.org/docs/ClangFormat.html[clang-format],
  * frontend: https://prettier.io/[prettier], https://eslint.org/[eslint]

GitHub does not support two things:

  * When a workflow runs when another workflow has finished, the result is not added to the status of the commit. https://github.com/bansan85/action-workflow_run-status[action-workflow_run-status] fix it.
  * The start of a workflow that runs on `completed` event does not depend on the success or the failure of the previous workflow. Use the following code to fix it.

[source,yml]
----
      - name: Stop if format failed
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: exit 1
----

=== Linters

Lots (maybe too much) of linters are used:

  * yaml: https://github.com/adrienverge/yamllint[yamllint],
  * bash: https://github.com/koalaman/shellcheck[shellcheck],
  * requirements.txt: https://github.com/pyupio/safety[safety],
  * c++: https://include-what-you-use.org/[iwyu], http://cppcheck.sourceforge.net/[cppcheck], https://clang.llvm.org/extra/clang-tidy/[clang-tidy].
  * javascript: https://eslint.org/[ESLint],
  * css: https://stylelint.io/[stylelint],
  * html: https://prettier.io[prettier],
  * python: https://pylint.org/[pylint], https://flake8.pycqa.org/en/latest/[flake8], http://prospector.landscape.io/en/master/[prospector], http://mypy-lang.org/[mypy]

=== Sanitizers

Enable all sanitizers: address, thread, leak, undefined, cfi.

=== Data generated

I decided to use my own interface in addition to other well-integrated softwares like https://codecov.io[codecov] to keep data under control.

All data are stored in https://github.com/bansan85/jessica-ci[jessica-ci] repository.

Every commit, following data are generated:

[cols="1,1,3"] 
|===
|Data |Git branch |Description

|Tests
|ubuntu-clang,
ubuntu-gcc,
windows-msbuild,
emscripten.
|Duration of each tests,
List of installed packages for Linux.

|Coverage
|coverage-clang,
coverage-gcc.
|Coverage information.
Should be the same with both compilers.

|Documentation
|documentation
|HTML documentation.

|Metrics
|metrics
|Complexity and length of functions.

|===
