:last-update-label!:
:source-highlighter: highlight.js
:highlightjsdir: highlight

= Building

== Dependencies

=== Building

Tools needed:

  * Compiler: gcc, clang or Visual Studio,
  * https://cmake.org/[cmake].

=== Backend

No dependencies.

=== Tests

You need:

  * https://github.com/google/googletest[gtest].

== Continuous integration

=== Building

The build is tested with Ubuntu-LTS with gcc and clang and Windows with Visual Studio.

  * Linux

Compilers tested : gcc-10 and clang-11.

Packages are installed with ''apt-get''.

  * Windows

Compilers tested : Visual Studio 2019.

Packages are installed with ''vcpkg''.

=== Auto formatting

Don't spend to much time about formatting. Continuous integration will automatically create commit to fix them with https://github.com/cheshirekow/cmake_format[cmake-format] and https://clang.llvm.org/docs/ClangFormat.html[clang-format].

This is done in the `linters` workflow. If a file need to be formatted, a new commit is added with a fix and the current build will fail.

=== Linters

Lots (maybe too much) of linters are used:

  * yml: https://github.com/adrienverge/yamllint[yamllint],
  * sh: https://github.com/koalaman/shellcheck[shellcheck],
  * requirements.txt: https://github.com/pyupio/safety[safety],
  * cc : https://include-what-you-use.org/[iwyu], http://cppcheck.sourceforge.net/[cppcheck], https://clang.llvm.org/extra/clang-tidy/[clang-tidy].

=== Data generated

I decided to use my own interface and not other well-integrated softwares like https://codecov.io[codecov] or https://codescene.io[codescene] to keep data under control.

All data are stored in https://github.com/bansan85/jessica-ci[jessica-ci] repository.

Every commit, following data are generated:

[cols="1,1,3"] 
|===
|Data |Git branch |Description

|Tests
|ubuntu-clang,
ubuntu-gcc,
windows-msbuild.
|Duration of each tests,
List of installed packages for Linux.

|Coverage
|coverage-clang,
coverage-gcc.
|Coverage information.
Should be the same with both compilers.

|Documentation
|documentation
|HTML documentation.

|Metrics
|metrics
|Complexity and length of functions.

|===
