:last-update-label!:
:source-highlighter: highlight.js
:highlightjsdir: highlight

= Coding style

== General rule

The https://google.github.io/styleguide/cppguide.html[Google C++ Style Guide] must be apply.

Rule in the current paragraph is a reminder of the official guide.

=== Naming convention

  * Filename: lower case with underline between words (i.e. `file_name.cc`),
  * Classe: camel case (i.e. `LoadClass`),
  * Function: camel case (i.e. `ExecuteRule`).
  * Accessors (getter / setter) do not use prefix `Get` and `Set`. Use the `f` function pattern described in Architecture file to use decorator.

  * Extension:
    ** C++ source: `.cc` and `.h`,
    ** Asciidoc: `.adoc`,
    ** yaml: `.yml`.

Do not use abbreviation.

== More formatting rules

=== Formatting files

Use LF as end of line. A choice must be done between Windows and Linux. Shorter is better and easier.

The main formating code I don't respect in Google standard is that all brackets are in new line. Only exception if both opening and closing bracket are in same line.

=== License

Writing license header on each source file is only mandatory for GPL.
For the MIT licence, there is only a copy in the file LICENSE.md.

== More coding style

=== Namespace

All symbols have a main namespace `Jessica`.

=== Functional programming

The software use functional programming when possible. Why ? Because I want to try it but only in interesting part of the software.

Getter and Setter are const. Setter return `std::shared_ptr`.

Functional programming makes all data const, so delete or make private / protected move constructor and move assignment.

=== Dependencies

Avoid deep dependencies.
If you use external dependency for just a few functions that could be easily replaced by another library, create an header adapter. See `jessica/test/test.h` for example.

=== Avoid...

  * ...too much symbol.

Use anonymous namespace where possible.
