---
name: format
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout@v2 with token
        uses: actions/checkout@v2
        if: ${{ github.event_name == 'push' }}
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: checkout@v2 without token
        uses: actions/checkout@v2
        if: ${{ github.event_name != 'push' }}
      - name: Install SSH key
        if: ${{ github.event_name == 'push' }}
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GITHUBCI_PRIVATE_KEY }}
          known_hosts: localhost ssh-rsa ${{ secrets.GITHUBCI_KNOW_HOSTS }}
      - name: Configure git
        run: |
          git config --global user.name "Github CI"
          git config --global user.email "github-ci@le-garrec.fr"
      - name: Configure git with token
        if: ${{ github.event_name == 'push' }}
        run: |
          eval `ssh-agent`
          ssh-add ~/.ssh/id_rsa
          gpg --version
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.ENCRYPT_PASSWORD }}" --output .github/encrypted/github-ci-private.key .github/encrypted/github-ci-private.key.gpg
          gpg --import .github/encrypted/github-ci-private.key
      - name: 3rdparty
        run: sudo apt-get update && sudo apt-get install -yq clang-12 clang-format-12
      - name: Set up Python "3.9"
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install python modules dependencies
        run: |
          python -m pip install --upgrade pip pipdeptree wheel
          pip install -r requirements-linter.txt
          pipdeptree -f > requirements-linter-ci.tmp
          diff -pu requirements-linter.txt requirements-linter-ci.tmp
      - name: Install node dependencies
        run: |
          npm install eslint eslint-config-google eslint-plugin-html
      - name: Publish data from CI
        if: ${{ github.event_name == 'push' }}
        run: |
          git clone --depth 1 ssh://git@github.com/bansan85/jessica-ci.git -b format
          rm -Rf jessica-ci/*
          apt list --installed > jessica-ci/apt-installed.txt
          eval `ssh-agent`
          ssh-add ~/.ssh/id_rsa
          gpg --version
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.ENCRYPT_PASSWORD }}" --output .github/encrypted/github-ci-private.key .github/encrypted/github-ci-private.key.gpg
          gpg --import .github/encrypted/github-ci-private.key
          cd jessica-ci || exit 1
          git add .
          if [ -n "$(git diff-index --name-only HEAD --)" ]; \
          then \
            git commit -S${{ secrets.GPG_KEY_ID }} -m "${{ github.event.head_commit.message }}" -m "Update from bansan85/jessica@$GITHUB_SHA"; \
            git push || { echo "Failure git push" && exit 1; } \
          fi
          cd .. || exit 1
          rm -Rf jessica-ci
      - name: formatter
        shell: bash
        run: |
          bash ./.github/scripts/format.sh
      - name: Fix formatting with token
        if: ${{ github.event_name == 'push' }}
        shell: bash
        run: |
          git add .
          if [ -n "$(git diff-index --name-only HEAD --)" ]; \
          then \
            git commit -S${{ secrets.GPG_KEY_ID }} -m "Fix formatting $GITHUB_SHA" ; \
            git push || { echo "Failure git push" && exit 1; }; \
            exit 1; \
          fi
      - name: Fix formatting without token
        if: ${{ github.event_name != 'push' }}
        shell: bash
        run: |
          git add .
          if [ -n "$(git diff-index --name-only HEAD --)" ]; \
          then \
            git commit -m "Fix formatting $GITHUB_SHA" ; \
            git push || { echo "Failure git push" && exit 1; }; \
            exit 1; \
          fi
