---
name: linters
on:
  workflow_run:
    workflows: ["format"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Stop if format failed
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: exit 1
      - uses: bansan85/action-workflow_run-status@main
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: 3rdparty
        run: sudo apt-get update && sudo apt-get install -yq libgtest-dev cppcheck iwyu shellcheck clang-tidy-10 clang-10
      - name: Set up Python "3.9"
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install python modules dependencies
        run: |
          python -m pip install --upgrade pip pipdeptree wheel
          pip install -r requirements-linter.txt
          pipdeptree -f > requirements-linter-ci.tmp
          diff -pu requirements-linter.txt requirements-linter-ci.tmp
      - name: Install node dependencies
        run: |
          npm install eslint eslint-config-google eslint-plugin-html
      - name: run-clang-tidy
        env:
          CC: clang-10
          CXX: clang++-10
        run: |
          mkdir build
          cmake -S . -B build
          cd build || exit 1
          run-clang-tidy-10
          cd .. || exit 1
      - name: Lint
        run: |
          bash ./.github/scripts/linters.sh
