---

name: linters

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - name: Install SSH key
              if: ${{ github.event_name == 'push' }}
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.GITHUBCI_PRIVATE_KEY }}
                  # get with ssh-keyscan localhost
                  known_hosts: localhost ssh-rsa ${{ secrets.GITHUBCI_KNOW_HOSTS }}
            - name: Set up Python "3.9"
              uses: actions/setup-python@v2
              with:
                  python-version: "3.9"
            - name: Install binaries dependencies
              run: sudo apt-get install shellcheck
            - name: Install python modules dependencies
              run: |
                  python -m pip install --upgrade pip pipdeptree wheel
                  pip install -r requirements-linter.txt
                  pipdeptree -f > requirements-linter-ci.txt
                  diff -pu requirements-linter.txt requirements-linter-ci.txt
            - name: Lint
              run: |
                  bash ./.github/scripts/linters.sh
