---
name: Sanitizer
on:
  workflow_run:
    workflows: ['format']
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - sanitizer: address
            ar: /usr/bin/ar
            cc: /usr/bin/gcc-11
            cxx: /usr/bin/g++-11
            ranlib: /usr/bin/ranlib
          - sanitizer: thread
            ar: /usr/bin/ar
            cc: /usr/bin/gcc-11
            cxx: /usr/bin/g++-11
            ranlib: /usr/bin/ranlib
          - sanitizer: leak
            ar: /usr/bin/ar
            cc: /usr/bin/gcc-11
            cxx: /usr/bin/g++-11
            ranlib: /usr/bin/ranlib
          - sanitizer: undefined
            ar: /usr/bin/ar
            cc: /usr/bin/gcc-11
            cxx: /usr/bin/g++-11
            ranlib: /usr/bin/ranlib
          - sanitizer: address
            ar: /usr/bin/llvm-ar-13
            cc: /usr/bin/clang-13
            cxx: /usr/bin/clang++-13
            ranlib: /usr/bin/llvm-ranlib-13
          - sanitizer: thread
            ar: /usr/bin/llvm-ar-13
            cc: /usr/bin/clang-13
            cxx: /usr/bin/clang++-13
            ranlib: /usr/bin/llvm-ranlib-13
          - sanitizer: leak
            ar: /usr/bin/llvm-ar-13
            cc: /usr/bin/clang-13
            cxx: /usr/bin/clang++-13
            ranlib: /usr/bin/llvm-ranlib-13
          - sanitizer: undefined
            ar: /usr/bin/llvm-ar-13
            cc: /usr/bin/clang-13
            cxx: /usr/bin/clang++-13
            ranlib: /usr/bin/llvm-ranlib-13
          - sanitizer: cfi
            ar: /usr/bin/llvm-ar-13
            cc: /usr/bin/clang-13
            cxx: /usr/bin/clang++-13
            cxx_flags: -flto=thin -fvisibility=hidden -fno-sanitize-trap=cfi
            ld_flags: -fuse-ld=gold
            ranlib: /usr/bin/llvm-ranlib-13
    steps:
      - name: Stop if format failed
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: exit 1
      - uses: bansan85/action-workflow_run-status@main
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ github.event.workflow_run.head_commit.id }}
      - name: Update apt-get
        run: |
          sudo sed -i "s/focal/impish/g" /etc/apt/sources.list
          sudo apt-get update
      - name: Install gcc
        if: contains(matrix.cc, 'gcc')
        run: sudo apt-get install -yq g++-11 gcc-11
      - name: Install clang
        if: contains(matrix.cc, 'clang')
        run: sudo apt-get install -yq clang-13 llvm-13
      - name: Install 3rdparty
        run: xargs -a config/apt-get.txt sudo apt-get install -yq
      - name: Fix cfi
        if: ${{ matrix.sanitizer == 'cfi' }}
        run: |
          sudo sed -i 's/_M_ptr() .*/\0 __attribute__((__no_sanitize__("cfi")))/g' /usr/include/c++/*/ext/aligned_buffer.h
          sudo sed -i 's/__base)/\0 __attribute__((__no_sanitize__("cfi")))/g' /usr/include/c++/*/ext/string_conversions.h
      - name: cmake
        run: |
          mkdir build
          cmake -S . -B build -DCMAKE_C_COMPILER="${{ matrix.cc }}" -DCMAKE_CXX_COMPILER="${{ matrix.cxx }}" -DCMAKE_CXX_FLAGS="-fsanitize=${{ matrix.sanitizer }} -fno-omit-frame-pointer -g -O0 ${{ matrix.cxx_flags }}" -DCMAKE_EXE_LINKER_FLAGS="${{ matrix.ld_flags }} -Wl,-O0" -DCMAKE_AR="${{ matrix.ar }}" -DCMAKE_RANLIB="${{ matrix.ranlib }}"
          cmake --build build/ --target all --config Release
      - name: ctest
        shell: bash
        run: |
          cd build || exit 1
          ctest --output-on-failure --verbose
          cd .. || exit 1
