---
name: Scan-build
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - name: Install SSH key
              if: ${{ github.event_name == 'push' }}
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.GITHUBCI_PRIVATE_KEY }}
                  known_hosts: localhost ssh-rsa ${{ secrets.GITHUBCI_KNOW_HOSTS }}
            - name: Install clang
              run: sudo apt-get update && sudo apt-get install -yq clang-11 clang-tools-11
            - name: Install 3rdparty
              run: sudo apt-get update && sudo apt-get install -yq libgtest-dev
            - name: cmake
              run: |
                  mkdir build scan-build-output
                  scan-build-11 -o scan-build-output cmake -S . -B build -DCMAKE_C_COMPILER=/usr/bin/clang-11 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-11 -DCMAKE_AR=/usr/bin/llvm-ar-11 -DCMAKE_RANLIB=/usr/bin/llvm-ranlib-11
                  scan-build-11 -o scan-build-output cmake --build build/ --target all
            - name: Publish result
              if: ${{ github.event_name == 'push' }}
              run: |
                  eval `ssh-agent`
                  git clone --depth 1 ssh://git@github.com/bansan85/jessica-ci.git -b scan-build
                  rm -Rf jessica-ci/*
                  find scan-build-output -mindepth 2 -maxdepth 2 -exec cp -R {} jessica-ci \;
                  ssh-add ~/.ssh/id_rsa
                  gpg --version
                  gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.ENCRYPT_PASSWORD }}" --output .github/encrypted/github-ci-private.key .github/encrypted/github-ci-private.key.gpg
                  gpg --import .github/encrypted/github-ci-private.key
                  cd jessica-ci || exit 1
                  git config --global user.name "Github CI"
                  git config --global user.email "github-ci@le-garrec.fr"
                  git add .
                  if [ -n "$(git diff-index --name-only HEAD --)" ]; \
                  then \
                    git commit -S${{ secrets.GPG_KEY_ID }} -m "${{ github.event.head_commit.message }}" -m "Update from bansan85/jessica@$GITHUB_SHA"; \
                    git push || { echo "Failure git push" && exit 1; } \
                  fi
                  cd .. || exit 1
